Dev
Padalchik/NewFormApi pull request #2
Opened 2024-12-20 18:08 UTC by Padalchik

2024-12-23 09:34 UTC, AntonyNET requested changes

2024-12-23 09:34 UTC, AntonyNET commented on Services/ProfileService.cs
> +                FirstName   = candiate.FirstName,
для чего в анкете добавлены дублирующие поля с ФИО кандидата?

2024-12-23 13:07 UTC, Padalchik commented on Services/ProfileService.cs
> +                FirstName   = candiate.FirstName,
@AntonyNET 
Бизнес требование  => в течении жизни ФИО человека может измениться => меняется ФИО у Анкеты, а не у Кандидата.

2024-12-24 19:24 UTC, AntonyNET approved these changes

2024-12-25 09:16 UTC, merged